### ISSUE TITLE
*.iml should be ignore

### ISSUE THREAD

**Issue by xcodebuild** [SimplyY/JnPlants#1]
See http://stackoverflow.com/questions/16736856/what-should-be-in-my-gitignore-for-an-android-studio-project,you can update your `.gitignore` file.

**Comment by SimplyY** [comment]
solved

**Comment by xcodebuild** [comment]
But where is the commit?

**Comment by SimplyY** [comment]
push失败了。。。

**Comment by SimplyY** [comment]
ok 了
