### ISSUE TITLE
搜索功能细分成任务

### ISSUE THREAD

**Issue by littletomato** [SimplyY/JnPlants#11]
搜索词：植物名字
搜索结果：具体的植物、美景列表

**Comment by littletomato** [comment]
1. 数据库  #13
2. ui设计 #12 
3. 功能设计 #14 
4. ui实现
5. 功能实现

**Comment by IwilsOday** [comment]
1. 数据库
- 分析
2 .ui设计
3. ui实现
4. 功能实现

**Comment by SimplyY** [comment]
#13
