### ISSUE TITLE
数据库设计

### ISSUE THREAD

**Issue by littletomato** [SimplyY/JnPlants#13]
数据库步骤：
- [x] 数据库设计
- [ ] 写十个样本
- [ ] 创建数据库
- [ ] 将样本录入数据库

植物数据源：
- [ ] 去基建处要数据源

美景数据源：
- [ ] 自己整理美景

**Comment by littletomato** [comment]
### 数据库结构设计

#### 植物信息表：

植物编号（plant ID） 名称（name） 别称（another_ name） 是否开花（is_blossom）学校相对地址（address） 经度（longitude）纬度（latitude) 描述（description）
不可为空：plant ID、name、address、longitude、latitude、description
可为空：another_ name、is_blossom、

#### 美景专辑信息表：

不可为空：title、article、author、season、date、hasChecked
可为空: lovers（list）、comments（list）

#### 美景图片表：

图片编号（picture ID）URL  图片名称（picture name）图片概述（picture description）
不可为空：picture ID、URL、picture name、picture description
####评论表：图片编号（picture ID）用户编号（user ID）评论时间（time）内容（content）头像（head picture）
不可为空：picture ID、user ID、time、content、head picture

#### 用户表：

用户编号（user ID）用户姓名（users  name）用户昵称（users_another_name)头像（head picture）
不可为空：user ID、users name、head picture
可为空：users_another_name

**Comment by SimplyY** [comment]
用户，允许第三方登陆

**Comment by SimplyY** [comment]
- [ ] 优化表结构
- [ ] 录入常见的植物数据
