### ISSUE TITLE
搜索功能设计

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#14]

**Comment by putiwangsheng** [comment]
搜索功能设计：
1. 点击侧滑栏的搜索植物，进入搜索页面。
2. 搜索页面包含搜索栏和热门搜索植物，点击热门搜索可以进入单个植物页面。
3. 点击搜索，输入要搜索的植物名称。下面的热门搜索植物隐藏。
4. 搜索结果为与所搜索的植物相近的植物列表，点击单个植物列表可以进入单个植物页面。

**Comment by putiwangsheng** [comment]
搜索
![image](https://cloud.githubusercontent.com/assets/8708202/8270937/db6e68ce-182f-11e5-9fc9-ee422a3af7d0.png)

**Comment by SimplyY** [comment]
暂时close，下一阶段再开发
