### ISSUE TITLE
（主页）美景功能的开发

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#16]
美景功能作为主页，安卓端

单个美景页面和评论页面，web端。
### 进度：
- [x] ui、功能设计
- [x] 数据库设计
- [x] 安卓端实现
- [x] web实现

**Comment by putiwangsheng** [comment]
### 美景功能设计：

#### 单个美景页面

单个页面可以进行点赞，评论。

#### ui设计

如下，需要p图，改颜色

**Comment by putiwangsheng** [comment]
投稿在手机上完成

**Comment by putiwangsheng** [comment]
![image](https://cloud.githubusercontent.com/assets/8708202/8270929/fac74840-182e-11e5-8bfb-6f740b08149b.png)

**Comment by putiwangsheng** [comment]
![image](https://cloud.githubusercontent.com/assets/8708202/8270930/219a61c8-182f-11e5-9098-71cde29c210b.png)

**Comment by putiwangsheng** [comment]
![image](https://cloud.githubusercontent.com/assets/8708202/8270937/db6e68ce-182f-11e5-9fc9-ee422a3af7d0.png)

**Comment by putiwangsheng** [comment]
# ui

## 首页

登录过后原来的地方会变成用户头像。
![image](https://cloud.githubusercontent.com/assets/8708202/10115871/51348ddc-644c-11e5-91e2-aa11d04e7f56.png)

## 单个美景页面

![image](https://cloud.githubusercontent.com/assets/8455579/10038712/ec228d88-61fb-11e5-97a8-aff8ef0ce860.png)

## 评论页面

![](http://s1.momo.moda/2015/06/21/8b6dd7db9af49e67306feb59a8bdc52c.png)

**Comment by SimplyY** [comment]
## 美景list
1. 首先是发送 http 请求获取最新 美景list
2. 与本地数据库核查
3. 假如不是最新数据，应该去后端下载数据（包括图片，list 信息等）
4. 如果是最新数据，直接去数据库读取数据
5. 填充数据到 listview 中。

#### 图片
1. 需要将图片下到 sd 卡，记录保存到的文件路径。
2. 以后通过文件路径找到图片
