### ISSUE TITLE
集体开发开会记录

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#17]
这里写上，自己干了什么，还有什么没干，需要多久干完。

**Comment by putiwangsheng** [comment]
已完成：
1. 完成搜索功能和美景功能设计
2. 参照礼物说和知乎，确定搜索和页面美景页面ui

待完成：
- [ ] 对ui的细节修改
- [ ] 给ui图加上注释

**Comment by littletomato** [comment]
#### 已完成
1. 完成了部分数据库结构的设计，还需改进
   #13
2. 寻找ssh key 还有一些问题

#### 未完成
- [ ] 数据库设计的进一步完善
- [ ] 安卓的熟悉
