### ISSUE TITLE
6.20 会议之写写每个人的动力

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#2]
#### 决定任何事能做到的程度

有一个ted视频，大家回去可以看看 http://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action.html
里面提出了 **why>how>what**
#### 第一件事，每个人找到自己做项目的动力。

• 从现在起大家要对大创提高一级警惕，在拖下去，轻则和其他大创一样，每天赶工。重则万一结不了题，报销款项都会被追回。
• 大创对在座的每一个人都很重要，无论是找工作还是去保研考研，这是我们在校参加的最高级别项目，可以写到简历的，但是因为有个普遍现象是江大大创大部分几乎是队长一个人做的，所以人家还会问你们到底做了什么。
• 这个项目只要我们认真做完不加水分，是涉及到很多高难度、有含金量的东西的，将近1w行的安卓程序、图像识别、web后端、团队合作开发，这些随便哪一个一届计科毕业生中没几个能搞定，更何况我们的项目全部都有，只要认真做，以后把这个写到简历绝对是个别人没有的加分项，更何况还可以学到很多东西，而这些东西在课堂是**绝对学不到**的，好多老师自己都不会，会的也会考虑学生的层次——说了也没几个人听。
#### 每个人说一下自己现在来作这个大创项目的理由

为什么来做这个大创项目，也就是动力，

**Comment by SimplyY** [comment]
每个人把自己的动力写到这里。

> （尝试用markdown格式来写，和在issue里面通过复制粘贴来“上传”图片）

**Comment by SimplyY** [comment]
我先写写我的动力吧
1. 我明年要准备各大公司的3月份暑假实习生面试，会去刷算法，刷面试题，要刷好几本书，估计没多少时间敲代码和参与大创，所以今年年底项目方面的代码一定要完成。
2. 简历上终于可以挂一个代码量上万行的项目。
3. 深入学习安卓、web后端，学习架构和学习如何高效团队开发。

**Comment by IwilsOday** [comment]
![image](https://cloud.githubusercontent.com/assets/9266909/8265668/309d85a0-1736-11e5-8975-01ddb7167f7e.png)

**Comment by littletomato** [comment]
### 我的动力：
1. 希望在大学学点真正有用的东西，然后工作的时候尽量专业对口
2. 已经要大三，留下来给我们积累的时间已经不多

**Comment by littletomato** [comment]
![image](https://cloud.githubusercontent.com/assets/10340566/8265671/61be0fc4-1736-11e5-873f-fd690647dfff.png)

**Comment by fujian-zfj** [comment]
1、大创对于保研有一定的帮助，以及以后的工作都有相应的帮助
2、大三的事情可能会更多，要把握有效的时间完成相应的任务

**Comment by putiwangsheng** [comment]
1..因为我是不想考研，毕业后直接工作，所以想现在多学习一些知识和技能。
2.参加大创对以后找工作会有很大的帮助，可以过上自己想要的生活。
