### ISSUE TITLE
关于阅读KillExam的问题列表

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#20]
大家在这里写下阅读我java大作业的安卓程序的困惑，以及我会在这里给出解答
项目地址 https://github.com/jnSimpler/KillExam
包括源代码和文档和安装包的下载地址，http://pan.baidu.com/s/1kT1lYBX

**Comment by SimplyY** [comment]
这里有关intent传数据的用法 https://github.com/SimplyY/web_piano/issues/25

**Comment by putiwangsheng** [comment]
### Intent笔记

Intent和Bundle用于Activity之间传递数据
- 用intent的putExtra(key,value)方法将数据以键值对的形式存入Intent
- Bundle来从Intent中读取数据，用bundle.getExtra()获得。
