### ISSUE TITLE
9.24日到10.10的开发进度交流

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#23]
### web：
- [x] 数据接口
- [x] 单个美景页面
- [x] 服务器搭建
### 安卓：
- [ ] 发送http请求 学习资料：https://github.com/SimplyY/JnPlants/issues/18 ，接收response回来的数据(用户信息、美景 list 等)。
- [ ] 拍照，图片处理(然后计算一些基本的特征值)
- [ ] 首页(功能按钮来切换到其他activity，美景list，点击进入webview)
- [ ] 数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)

**Comment by SimplyY** [comment]
# web组

> 更新时间 9.29

## 开发进度

完成：
1. web后端框架使用
2. 服务器搭建
3. 域名备案

即将：
1. 图床页面，用于投稿的上传图片
2. 投稿功能（只支持桌面端）
3. 开发美景功能的评论功能
4. 增加数据接口的安全加密

## 开发需求
1. 美景数据（照片，林超）

**Comment by littletomato** [comment]
## 安卓组

### 已完成

 主页UI大体完成

### 即将
- [x] searchbar 置顶
- [x] 从web后端获取美景 list数据，首先用测试数据
- [x] 将数据存到数据库

### 需求
1. 登录界面UI
2. 后端提供美景 list 的接口（余伟）

**Comment by putiwangsheng** [comment]
## UI组

> 更新时间：10.7

### 已完成：

投稿界面大致UI设计。

### 即将：

评论界面UI。

### 需求：

确定软件的主色调。

**Comment by IwilsOday** [comment]
# 王莉

## 进度

服务器已经买好，坐等寄来发票，再进行后续处理。

## 即将：
1. 列出报销已占用费用和报销额度清单
2. 十一后报销所有发票。
3. 联系肖老师，咨询住宿证明、盖章等所有事宜。
4. 将开会的时间固定化、规则化。
5. 采摘好10种叶子跟班主任联系。

## 下次开会是否要设定在国庆后

**Comment by SimplyY** [comment]
# 林超

## 进度
1. 已完成：
   所有图片已经设置宽为800的图片 并按照地点-数字重命名
2. 即将：十一之后去基建处联系老师，取得数据资料

**Comment by fujian-zfj** [comment]
# android组UI

## 主页开发

  模仿QQ的搜索框,点击后置顶

## 已完成（10月5号晚）

   点击搜索框置顶，并打开输入法，标题栏动画效果为上移，返回键或是取消TextView都可以返回到主页面，所用为PopupWindow，这个弹出框是悬浮在当前activity之上的。
![image](https://cloud.githubusercontent.com/assets/10379042/10298149/afd8fe9a-6c0d-11e5-8969-d8ca5f9aaf98.png)

## 将要进行的开发

> 1、 登陆界面的UI
> 2、主页ListView内容的填充

## 需求

 登陆界面的UI
