### ISSUE TITLE
总需求以及大进度

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#3]

**Comment by IwilsOday** [comment]
1. 江南大学植物分布图
2. 基于GPS寻找周边植物
3. 根据名字搜索植物
4. 校园美景推荐
5. 通过对拍照扫描分辨植物算法的深入研究，争取完成“拍照搜索植物”的功能
6. 植物在线询问（首页）

**Comment by SimplyY** [comment]
小学期，首先完成的需求

根据名字搜索植物
校园美景推荐
