### ISSUE TITLE
九月已完成工作的报告

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#30]
应老师要求，我们每个人在这里写好，王莉负责整理。

**Comment by SimplyY** [comment]
## web 后端：
1. 服务器的基本功能搭建
2. 域名备案（已提交申请，正在审核）
3. 后端 api 化雏形完成：能通过 http 请求操作数据库的数据
4. 正在开发web 端的qq 第三方登陆：获取 qq 信息，以此为数据搭建以后的用户系统

**Comment by putiwangsheng** [comment]
## UI及web前端：
1. UI方面：完成安卓首页、单个美景，电脑端投稿网页界面的设计。
2. web前端：单个美景页面，投稿页面的ui编写基本完成。
3. 投稿页面交互功能实现后即将进行评论页面和收藏页面的UI设计。

**Comment by fujian-zfj** [comment]
## android：
1. 应用主页基本写完（具体功能有待实现）
2. 仿QQ搜索框完成，主页ListView内容有待填充
3. QQ第三方登录实现
4. 获取QQ账号个人信息（昵称、头像）完成，有待建立数据存储个人信息
