### ISSUE TITLE
地图功能

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#33]
我突然觉得，，地图功能的需求很低很低啊，，感觉会几乎没人用，，我们这次开会分析一下要不要这个功能吧，

**Comment by SimplyY** [comment]
我觉得要不就不要了，
原因
1. 手机小，能展示的东西有限
2. 开发复杂，使用地图 sdk 和定位等
3. 基本没需求，江大虽然很大，但稍微走走就知道各处的地点了
4. 美景和植物页面应该对方位有所介绍

**Comment by IwilsOday** [comment]
### 班主任说必须完成~~~

**Comment by SimplyY** [comment]
那就定到期末考试结束就开发
