### ISSUE TITLE
中期检查

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#38]
截止到2015.９月底已经完成的成果为：
web 后端：
1.  服务器的基本功能搭建
2.  域名备案（已提交申请，正在审核）
3.  后端 api 化雏形完成：能通过 http 请求操作数据库的数据
4.  正在开发web 端的qq 第三方登陆：获取 qq 信息，以此为数据搭建以后的用户系统
UI及web前端：
1.  UI方面：完成安卓首页、单个美景，电脑端投稿网页界面的设计。
2.  web前端：单个美景页面，投稿页面的ui编写基本完成。
3.  投稿页面交互功能实现后即将进行评论页面和收藏页面的UI设计。
android：
1.  应用主页基本写完（具体功能有待实现）
2.  仿QQ搜索框完成，主页ListView内容有待填充
3.  QQ第三方登录实现
4.  获取QQ账号个人信息（昵称、头像）完成，有待建立数据存储个人信息
5.  完成了安卓调用照相机并记录储存位置的功能

截止到2015.１０月底已经完成的成果为：
Android组
已完成
• 将获取的QQ头像，昵称保存到本地
• 获取存储到本地的QQ头像，即当按下back键退出活动（onDestroy（））时，再次进入应用不必重新从网络上获取QQ头像，直接先判断本地是否有头像，若有，则直接获取
• 个人信息页面，获取本地数据库的用户头像和昵称并显示，右滑或是按下返回按钮退出个人页面
• 主页ListView美景内容获取成功，并将图片的棱角圆角化，点击item后进入相应的美景页面。
•  数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)
•  发送http请求 学习资料：#18 ，接收response回来的数据(用户信息、美景 list 等)。
•  首页(功能按钮来切换到其他activity，美景list，点击进入webview)
•  QQ第三方登录，获取账号信息并存入本地数据库
•  主页ListVIew美景内容的获取
成果展示：

Web组
完成
•  美景投稿页面 基本完成 #27
•  服务器端 数据库表建立和 restful 化：用户、评论、美景、植物
•  单个美景页面上线
成果展示：

UI组
已完成：软件logo

  美景list图片 

即将开始的图像识别组
正在
•  数据资料的收集
•  图像特征值的提取
已完成
1.  通过多途径收集所需美景照片（搜寻qq空间），同时联系了基建处方面，取得了他们的同意，获得了美景图片。同时对图片进行裁剪，压缩，分类等基础图片处理工作。
2.  已收集6种叶片，压平，准备拍照采集。
3.  初步学习了图像识别方面的知识，目前已经完成了图像的灰度化，以及尝试了多种图像分割的算法等图像预处理工作

**Comment by putiwangsheng** [comment]
#### UI及web前端

1.UI设计
- 软件logo
- 安卓首页，包括四个功能按钮的设计和美景列表的展示。
- 安卓单个美景页面，展示单个美景具体信息。
- 安卓个人页面，显示个人头像、昵称，喜欢的美景，喜欢的植物，接受的消息三个跳转按钮以及退出当前账号。
- 安卓评论页面，展示评论列表，列表展示评论人的头像昵称，评论内容及评论时间。
- 电脑端美景和植物投稿页面，主要包含三个部分：美景或者植物列表的展示，投稿区域，以及即时的预览。

2.web前端
- 已完成单个美景页面，评论页面，美景和植物投稿UI界面的编写。
- 单个美景页面，美景和植物投稿页面的交互已实现。
- 正在进行评论页面交互功能的编写。

**Comment by Allenen** [comment]
Android组
已完成
• 将获取的QQ头像，昵称保存到本地
• 获取存储到本地的QQ头像，即当按下back键退出活动（onDestroy（））时，再次进入应用不必重新从网络上获取QQ头像，直接先判断本地是否有头像，若有，则直接获取
• 个人信息页面，获取本地数据库的用户头像和昵称并显示，右滑或是按下返回按钮退出个人页面，“我喜欢的美景”功能模块实现，与主业的美景收藏原理相同，见下。
• 主页ListView美景内容获取成功，并将图片的棱角圆角化，点击item后进入相应的美景页面。
•  数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)
•  发送http请求 学习资料：#18 ，接收response回来的数据(用户信息、美景 list 等)。
•  首页(功能按钮来切换到其他activity，美景list，点击进入webview)
•  QQ第三方登录，获取账号信息并存入本地数据库
•  主页ListVIew美景内容的获取，并刷新添加新的美景
•  美景收藏页面完成，点击美景收藏图标，在登录的状态下进入收藏页面，并从服务器获取用户收藏的美景，展示在listview中。
•  个人
成果展示：

**Comment by Allenen** [comment]
Android组
已完成
• 将获取的QQ头像，昵称保存到本地
• 获取存储到本地的QQ头像，即当按下back键退出活动（onDestroy（））时，再次进入应用不必重新从网络上获取QQ头像，直接先判断本地是否有头像，若有，则直接获取
• 个人信息页面，获取本地数据库的用户头像和昵称并显示，右滑或是按下返回按钮退出个人页面，“我喜欢的美景”功能模块实现，与主业的美景收藏原理相同，见下。
• 主页ListView美景内容获取成功，并将图片的棱角圆角化，点击item后进入相应的美景页面。
•  数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)
•  发送http请求 学习资料：#18 ，接收response回来的数据(用户信息、美景 list 等)。
•  首页(功能按钮来切换到其他activity，美景list，点击进入webview)
•  QQ第三方登录，获取账号信息并存入本地数据库
•  主页ListVIew美景内容的获取，并刷新添加新的美景
•  美景收藏页面完成，点击美景收藏图标，在登录的状态下进入收藏页面，并从服务器获取用户收藏的美景，展示在listview中。
•  个人
成果展示：

**Comment by Allenen** [comment]
Android组
已完成
• 将获取的QQ头像，昵称保存到本地
• 获取存储到本地的QQ头像，即当按下back键退出活动（onDestroy（））时，再次进入应用不必重新从网络上获取QQ头像，直接先判断本地是否有头像，若有，则直接获取
• 个人信息页面，获取本地数据库的用户头像和昵称并显示，右滑或是按下返回按钮退出个人页面，“我喜欢的美景”功能模块实现，与主业的美景收藏原理相同，见下。
• 主页ListView美景内容获取成功，并将图片的棱角圆角化，点击item后进入相应的美景页面。
•  数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)
•  发送http请求 学习资料：#18 ，接收response回来的数据(用户信息、美景 list 等)。
•  首页(功能按钮来切换到其他activity，美景list，点击进入webview)
•  QQ第三方登录，获取账号信息并存入本地数据库
•  主页ListVIew美景内容的获取，并刷新添加新的美景
•  美景收藏页面完成，点击美景收藏图标，在登录的状态下进入收藏页面，并从服务器获取用户收藏的美景，展示在listview中。
•  个人
成果展示：

**Comment by Allenen** [comment]
Android组
已完成
• 将获取的QQ头像，昵称保存到本地
• 获取存储到本地的QQ头像，即当按下back键退出活动（onDestroy（））时，再次进入应用不必重新从网络上获取QQ头像，直接先判断本地是否有头像，若有，则直接获取
• 个人信息页面，获取本地数据库的用户头像和昵称并显示，右滑或是按下返回按钮退出个人页面，“我喜欢的美景”功能模块实现，与主业的美景收藏原理相同，见下。
• 主页ListView美景内容获取成功，并将图片的棱角圆角化，点击item后进入相应的美景页面。
•  数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)
•  发送http请求 学习资料：#18 ，接收response回来的数据(用户信息、美景 list 等)。
•  首页(功能按钮来切换到其他activity，美景list，点击进入webview)
•  QQ第三方登录，获取账号信息并存入本地数据库
•  主页ListVIew美景内容的获取，并刷新添加新的美景
•  美景收藏页面完成，点击美景收藏图标，在登录的状态下进入收藏页面，并从服务器获取用户收藏的美景，展示在listview中。
•  个人
成果展示：

**Comment by Allenen** [comment]
Android组
已完成
> 将获取的QQ头像，昵称保存到本地
? 获取存储到本地的QQ头像，即当按下back键退出活动（onDestroy（））时，再次进入应用不必重新从网络上获取QQ头像，直接先判断本地是否有头像，若有，则直接获取
? 个人信息页面，获取本地数据库的用户头像和昵称并显示，右滑或是按下返回按钮退出个人页面，“我喜欢的美景”功能模块实现，与主业的美景收藏原理相同，见下。
? 主页ListView美景内容获取成功，并将图片的棱角圆角化，点击item后进入相应的美景页面。
?  数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)
?  发送http请求 学习资料：#18 ，接收response回来的数据(用户信息、美景 list 等)。
?  首页(功能按钮来切换到其他activity，美景list，点击进入webview)
?  QQ第三方登录，获取账号信息并存入本地数据库
?  主页ListVIew美景内容的获取，并刷新添加新的美景
?  美景收藏页面完成，点击美景收藏图标，在登录的状态下进入收藏页面，并从服务器获取用户收藏的美景，展示在listview中。
?  个人
成果展示：

**Comment by fujian-zfj** [comment]
### Android组
1. 将获取的QQ头像，昵称保存到本地数据库
2. 获取存储到本地的QQ头像，再次进入应用不必重新从网络上获取QQ头像，直接先判断本地是否有头      像，若有，则直接获取
3. 个人信息页面，获取本地数据库的用户头像和昵称并显示，“我喜欢的美景”功能模块实现，与主业的美景收藏原理相同，见下。
4. 主页ListView美景内容获取成功，并将图片的棱角圆角化，点击item后进入相应的美景页面。
5.  数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)
6.  发送http请求 ，接收response回来的数据(用户信息、美景 list 等)。
7.  美景Listview的item点击进入单个美景页面
8. 主页ListVIew美景内容的获取,并刷新添加新的美景
9. 登录后进入美景收藏页面，显示用户收藏美景

**Comment by SimplyY** [comment]
## web 后端
1. 服务器的基本功能搭建，并使用 node.js 的 express 框架进行 web 后端开发
2. 域名备案已通过。
3. 通过使用 node-restful 和 mongodb 将后端 api restful化完成：能通过 http 请求操作服务器端数据库的数据
4. 允许qq 第三方登陆：获取 qq 信息，以此为数据搭建用户系统
5. 美景投稿页面基本完成
6. 服务器端 数据库各类存储数据的表建立：已完成用户、评论、美景、植物表
7. 单个美景页面上线

**Comment by SimplyY** [comment]
## 图像识别
1. 自学了一些图像处理相关的知识，了解到图像识别需要对图片进行预处理，例如灰度化，阈值分割。目前对于灰度化已经完成，阈值分割方面实现了算法，但对于目前图像的二值化处理，效果不是很理想。
2. 目前正在学习基于opencv在Android studio上进行gabor特征提取。由于对opencv以及Android studio上进行ndk开发不太熟悉，目前仍在学习

## 信息采集
1. 基建处拥有校园丰富的图片，所以需要与他们沟通获取帮助，另外联系江大知名拍客，选取优质富有代表性的图片
2. 负责前期图片的裁剪以及压缩

**Comment by IwilsOday** [comment]
### 王莉已完成
1.  按时组织小组成员开交流会，讨论出现的问题，按计划推进开发进程。
2.  推进报销进程和进度汇报。
3.  搜集了大量美景图片、10种叶子，对美景照片进行预处理和编辑上传，对叶子进行了分类、压平、拍照、裁剪，压缩等图片识别的预处理工作。
