### ISSUE TITLE
6.20 开会内容

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#5]
1. 写写自己的动力 #2 
2. 讨论产品和功能需求 #3 
3. 有关issue的使用方法 #4

**Comment by IwilsOday** [comment]
（1）江南大学植物分布图
（2）基于GPS寻找周边植物
（3）根据名字搜索植物
（4）校园美景推荐
（5)	通过对拍照扫描分辨植物算法的深入研究，争取完成“拍照搜索植物”的功能
