### ISSUE TITLE
小学期项目待解决的需求（搜索、美景）

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#6]
两大需求要在小学期解决：
- [ ] 根据名字搜索植物
- [ ] 校园美景推荐
#### 细分需求为任务
- [x] 这里集中写上讨论出的关于每个需求所需要的所有功能（比如ui视图，搜索查询）
- [x] 然后针对每个功能新开issue，在新的issue里面列出编程任务（todo list，比如建数据库，设计ui，写ui等）,每一项任务的时间估计单位为小时
- [ ] 认领任务（todo list 后面写上自己的名字）
- [ ] 完成任务（todo list点击打勾）

**Comment by SimplyY** [comment]
1. 敲代码分两组分别来弄不同的需求
2. 我、我妹子一组负责美景需求
3. 林超赵福建一组负责搜索需求
4. 王莉是产品经理决定ui和交互，我负责组织团队合作，我妹子负责ui设计。

**Comment by littletomato** [comment]
搜索
#11

**Comment by IwilsOday** [comment]
#5 
美景功能
